# Generated by Django 5.2.5 on 2026-09-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_seats_per_booking',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='event',
            name='min_seats_per_booking',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
