# Generated by Django 5.2.5 on 2026-09-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_max_seats_per_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_url',
            field=models.URLField(blank=True, default='', help_text='Optional URL to an event banner or poster image.'),
        ),
    ]
