# Generated by Django 5.2.5 on 2026-09-18 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number (7 to 15 digits, optional '+' country code prefix).", regex='^\\+?[0-9]{7,15}$')]),
        ),
    ]
